{
 "title": "Sustainability Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Lambda Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       ELcompute: ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) * (if exists r[\"assumed_P_core_w\"] then r[\"assumed_P_core_w\"] else 25.0) / (3600.0 * 1000.0),\n      ELmemory:  ((if exists r[\"lambda_DoorbellLambda_Mused\"] then r[\"lambda_DoorbellLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Mused\"] then r[\"lambda_FaceRecognitionLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Mused\"] then r[\"lambda_FetchWebsiteFromS3_Mused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Mused\"] then r[\"lambda_PINVerificationLambda_Mused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Mused\"] then r[\"lambda_UploadLambda_Mused\"] else 0.0)) * (if exists r[\"assumed_P_mem_w\"] then r[\"assumed_P_mem_w\"] else 10.0) * ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) / (1024.0 * 1000.0 * 3600.0),\n      ELstorage: ((if exists r[\"lambda_DoorbellLambda_Sused\"] then r[\"lambda_DoorbellLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Sused\"] then r[\"lambda_FaceRecognitionLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Sused\"] then r[\"lambda_FetchWebsiteFromS3_Sused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Sused\"] then r[\"lambda_PINVerificationLambda_Sused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Sused\"] then r[\"lambda_UploadLambda_Sused\"] else 0.0)) * (if exists r[\"assumed_P_storage_w\"] then r[\"assumed_P_storage_w\"] else 5.0) / (1073741824.0 * 1000.0 * 3600.0),\n      Enetwork:  ((if exists r[\"lambda_DoorbellLambda_Dnetwork\"] then r[\"lambda_DoorbellLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Dnetwork\"] then r[\"lambda_FaceRecognitionLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] then r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Dnetwork\"] then r[\"lambda_PINVerificationLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Dnetwork\"] then r[\"lambda_UploadLambda_Dnetwork\"] else 0.0)) * 0.277778 / 1073741824.0\n  }))\n  |> map(fn: (r) => ({ r with _value: r.ELcompute + r.ELmemory + r.ELstorage + r.Enetwork }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "S3 Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       ES3active: ((if exists r[\"s3_mhm-home-security-img_Rtotal\"] then r[\"s3_mhm-home-security-img_Rtotal\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Rtotal\"] then r[\"s3_mhm-home-security-ui_Rtotal\"] else 0.0)) * ((if exists r[\"s3_mhm-home-security-img_Dlatency\"] then r[\"s3_mhm-home-security-img_Dlatency\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Dlatency\"] then r[\"s3_mhm-home-security-ui_Dlatency\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      ES3idle:   ((if exists r[\"s3_mhm-home-security-img_B\"] then r[\"s3_mhm-home-security-img_B\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_B\"] then r[\"s3_mhm-home-security-ui_B\"] else 0.0)) * 0.0001 / (1073741824.0 * 1024.0 * 1000.0)\n  }))\n  |> map(fn: (r) => ({ r with _value: r.ES3active + r.ES3idle }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "DynamoDB Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       EDB: ((if exists r[\"dynamodb_Events_Lsuccess\"] then r[\"dynamodb_Events_Lsuccess\"] else 0.0) + (if exists r[\"dynamodb_Users_Lsuccess\"] then r[\"dynamodb_Users_Lsuccess\"] else 0.0)) * 0.005 / (3600.0 * 1000.0)\n  }))\n  |> map(fn: (r) => ({ r with _value: r.EDB }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "API Gateway Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       EAPI: (if exists r[\"api_API_LAPI\"] then r[\"api_API_LAPI\"] else 0.0) * 15.0 / (3600.0 * 1000.0)\n  }))\n  |> map(fn: (r) => ({ r with _value: r.EAPI }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Rekognition Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       ERekog: (if exists r[\"rekognition_Rekognition_Tresponse\"] then r[\"rekognition_Rekognition_Tresponse\"] else 0.0) * 50.0 / (3600.0 * 1000.0)\n  }))\n  |> map(fn: (r) => ({ r with _value: r.ERekog }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Total SCI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gCO2eq" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       ELcompute: ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) * (if exists r[\"assumed_P_core_w\"] then r[\"assumed_P_core_w\"] else 25.0) / (3600.0 * 1000.0),\n      ELmemory:  ((if exists r[\"lambda_DoorbellLambda_Mused\"] then r[\"lambda_DoorbellLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Mused\"] then r[\"lambda_FaceRecognitionLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Mused\"] then r[\"lambda_FetchWebsiteFromS3_Mused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Mused\"] then r[\"lambda_PINVerificationLambda_Mused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Mused\"] then r[\"lambda_UploadLambda_Mused\"] else 0.0)) * (if exists r[\"assumed_P_mem_w\"] then r[\"assumed_P_mem_w\"] else 10.0) * ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) / (1024.0 * 1000.0 * 3600.0),\n      ELstorage: ((if exists r[\"lambda_DoorbellLambda_Sused\"] then r[\"lambda_DoorbellLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Sused\"] then r[\"lambda_FaceRecognitionLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Sused\"] then r[\"lambda_FetchWebsiteFromS3_Sused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Sused\"] then r[\"lambda_PINVerificationLambda_Sused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Sused\"] then r[\"lambda_UploadLambda_Sused\"] else 0.0)) * (if exists r[\"assumed_P_storage_w\"] then r[\"assumed_P_storage_w\"] else 5.0) / (1073741824.0 * 1000.0 * 3600.0),\n      Enetwork:  ((if exists r[\"lambda_DoorbellLambda_Dnetwork\"] then r[\"lambda_DoorbellLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Dnetwork\"] then r[\"lambda_FaceRecognitionLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] then r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Dnetwork\"] then r[\"lambda_PINVerificationLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Dnetwork\"] then r[\"lambda_UploadLambda_Dnetwork\"] else 0.0)) * 0.277778 / 1073741824.0,\n      ES3active: ((if exists r[\"s3_mhm-home-security-img_Rtotal\"] then r[\"s3_mhm-home-security-img_Rtotal\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Rtotal\"] then r[\"s3_mhm-home-security-ui_Rtotal\"] else 0.0)) * ((if exists r[\"s3_mhm-home-security-img_Dlatency\"] then r[\"s3_mhm-home-security-img_Dlatency\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Dlatency\"] then r[\"s3_mhm-home-security-ui_Dlatency\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      ES3idle:   ((if exists r[\"s3_mhm-home-security-img_B\"] then r[\"s3_mhm-home-security-img_B\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_B\"] then r[\"s3_mhm-home-security-ui_B\"] else 0.0)) * 0.0001 / (1073741824.0 * 1024.0 * 1000.0)      ,\n      EDB:       ((if exists r[\"dynamodb_Events_Lsuccess\"] then r[\"dynamodb_Events_Lsuccess\"] else 0.0) + (if exists r[\"dynamodb_Users_Lsuccess\"] then r[\"dynamodb_Users_Lsuccess\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      EAPI:      (if exists r[\"api_API_LAPI\"] then r[\"api_API_LAPI\"] else 0.0) * 15.0 / (3600.0 * 1000.0),\n      ERekog:    (if exists r[\"rekognition_Rekognition_Tresponse\"] then r[\"rekognition_Rekognition_Tresponse\"] else 0.0) * 50.0 / (3600.0 * 1000.0),\n      PUE:       (if exists r[\"assumed_PUE\"] then r[\"assumed_PUE\"] else 1.5),\n      GEF:       (if exists r[\"grid_emission_factor\"] then r[\"grid_emission_factor\"] else 350.0)\n  }))\n  |> map(fn: (r) => ({\n      r with\n      ETotal: r.ELcompute + r.ELmemory + r.ELstorage + r.Enetwork + r.EDB + r.EAPI + r.ERekog + r.ES3active + r.ES3idle\n  }))\n  |> map(fn: (r) => ({\n      r with\n      SCI: r.ETotal * r.PUE * r.GEF\n  }))\n  |> map(fn: (r) => ({ r with _value: r.SCI }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Software Carbon Intensity (SCI)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       ELcompute: ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) * (if exists r[\"assumed_P_core_w\"] then r[\"assumed_P_core_w\"] else 25.0) / (3600.0 * 1000.0),\n      ELmemory:  ((if exists r[\"lambda_DoorbellLambda_Mused\"] then r[\"lambda_DoorbellLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Mused\"] then r[\"lambda_FaceRecognitionLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Mused\"] then r[\"lambda_FetchWebsiteFromS3_Mused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Mused\"] then r[\"lambda_PINVerificationLambda_Mused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Mused\"] then r[\"lambda_UploadLambda_Mused\"] else 0.0)) * (if exists r[\"assumed_P_mem_w\"] then r[\"assumed_P_mem_w\"] else 10.0) * ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) / (1024.0 * 1000.0 * 3600.0),\n      ELstorage: ((if exists r[\"lambda_DoorbellLambda_Sused\"] then r[\"lambda_DoorbellLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Sused\"] then r[\"lambda_FaceRecognitionLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Sused\"] then r[\"lambda_FetchWebsiteFromS3_Sused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Sused\"] then r[\"lambda_PINVerificationLambda_Sused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Sused\"] then r[\"lambda_UploadLambda_Sused\"] else 0.0)) * (if exists r[\"assumed_P_storage_w\"] then r[\"assumed_P_storage_w\"] else 5.0) / (1073741824.0 * 1000.0 * 3600.0),\n      Enetwork:  ((if exists r[\"lambda_DoorbellLambda_Dnetwork\"] then r[\"lambda_DoorbellLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Dnetwork\"] then r[\"lambda_FaceRecognitionLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] then r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Dnetwork\"] then r[\"lambda_PINVerificationLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Dnetwork\"] then r[\"lambda_UploadLambda_Dnetwork\"] else 0.0)) * 0.277778 / 1073741824.0,\n      ES3active: ((if exists r[\"s3_mhm-home-security-img_Rtotal\"] then r[\"s3_mhm-home-security-img_Rtotal\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Rtotal\"] then r[\"s3_mhm-home-security-ui_Rtotal\"] else 0.0)) * ((if exists r[\"s3_mhm-home-security-img_Dlatency\"] then r[\"s3_mhm-home-security-img_Dlatency\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Dlatency\"] then r[\"s3_mhm-home-security-ui_Dlatency\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      ES3idle:   ((if exists r[\"s3_mhm-home-security-img_B\"] then r[\"s3_mhm-home-security-img_B\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_B\"] then r[\"s3_mhm-home-security-ui_B\"] else 0.0)) * 0.0001 / (1073741824.0 * 1024.0 * 1000.0)      ,\n      EDB:       ((if exists r[\"dynamodb_Events_Lsuccess\"] then r[\"dynamodb_Events_Lsuccess\"] else 0.0) + (if exists r[\"dynamodb_Users_Lsuccess\"] then r[\"dynamodb_Users_Lsuccess\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      EAPI:      (if exists r[\"api_API_LAPI\"] then r[\"api_API_LAPI\"] else 0.0) * 15.0 / (3600.0 * 1000.0),\n      ERekog:    (if exists r[\"rekognition_Rekognition_Tresponse\"] then r[\"rekognition_Rekognition_Tresponse\"] else 0.0) * 50.0 / (3600.0 * 1000.0),\n      PUE:       (if exists r[\"assumed_PUE\"] then r[\"assumed_PUE\"] else 1.5),\n      GEF:       (if exists r[\"grid_emission_factor\"] then r[\"grid_emission_factor\"] else 350.0)\n  }))\n  |> map(fn: (r) => ({\n      r with\n      ETotal: r.ELcompute + r.ELmemory + r.ELstorage + r.Enetwork + r.EDB + r.EAPI + r.ERekog + r.ES3active + r.ES3idle\n  }))\n  |> map(fn: (r) => ({\n      r with\n      SCI: r.ETotal * r.PUE * r.GEF\n  }))\n  |> map(fn: (r) => ({ r with _value: r.SCI }))\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Total Energy Breakdown (kWh)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "query": "results = from(bucket: \"demo_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measured_metrics\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n      r with\n       ELcompute: ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) * (if exists r[\"assumed_P_core_w\"] then r[\"assumed_P_core_w\"] else 25.0) / (3600.0 * 1000.0),\n      ELmemory:  ((if exists r[\"lambda_DoorbellLambda_Mused\"] then r[\"lambda_DoorbellLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Mused\"] then r[\"lambda_FaceRecognitionLambda_Mused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Mused\"] then r[\"lambda_FetchWebsiteFromS3_Mused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Mused\"] then r[\"lambda_PINVerificationLambda_Mused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Mused\"] then r[\"lambda_UploadLambda_Mused\"] else 0.0)) * (if exists r[\"assumed_P_mem_w\"] then r[\"assumed_P_mem_w\"] else 10.0) * ((if exists r[\"lambda_DoorbellLambda_Texec\"] then r[\"lambda_DoorbellLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Texec\"] then r[\"lambda_FaceRecognitionLambda_Texec\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Texec\"] then r[\"lambda_FetchWebsiteFromS3_Texec\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Texec\"] then r[\"lambda_PINVerificationLambda_Texec\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Texec\"] then r[\"lambda_UploadLambda_Texec\"] else 0.0) + (if exists r[\"lambda_DoorbellLambda_Tinit\"] then r[\"lambda_DoorbellLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Tinit\"] then r[\"lambda_FaceRecognitionLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Tinit\"] then r[\"lambda_FetchWebsiteFromS3_Tinit\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Tinit\"] then r[\"lambda_PINVerificationLambda_Tinit\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Tinit\"] then r[\"lambda_UploadLambda_Tinit\"] else 0.0)) / (1024.0 * 1000.0 * 3600.0),\n      ELstorage: ((if exists r[\"lambda_DoorbellLambda_Sused\"] then r[\"lambda_DoorbellLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Sused\"] then r[\"lambda_FaceRecognitionLambda_Sused\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Sused\"] then r[\"lambda_FetchWebsiteFromS3_Sused\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Sused\"] then r[\"lambda_PINVerificationLambda_Sused\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Sused\"] then r[\"lambda_UploadLambda_Sused\"] else 0.0)) * (if exists r[\"assumed_P_storage_w\"] then r[\"assumed_P_storage_w\"] else 5.0) / (1073741824.0 * 1000.0 * 3600.0),\n      Enetwork:  ((if exists r[\"lambda_DoorbellLambda_Dnetwork\"] then r[\"lambda_DoorbellLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FaceRecognitionLambda_Dnetwork\"] then r[\"lambda_FaceRecognitionLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] then r[\"lambda_FetchWebsiteFromS3_Dnetwork\"] else 0.0) + (if exists r[\"lambda_PINVerificationLambda_Dnetwork\"] then r[\"lambda_PINVerificationLambda_Dnetwork\"] else 0.0) + (if exists r[\"lambda_UploadLambda_Dnetwork\"] then r[\"lambda_UploadLambda_Dnetwork\"] else 0.0)) * 0.277778 / 1073741824.0,\n      ES3active: ((if exists r[\"s3_mhm-home-security-img_Rtotal\"] then r[\"s3_mhm-home-security-img_Rtotal\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Rtotal\"] then r[\"s3_mhm-home-security-ui_Rtotal\"] else 0.0)) * ((if exists r[\"s3_mhm-home-security-img_Dlatency\"] then r[\"s3_mhm-home-security-img_Dlatency\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_Dlatency\"] then r[\"s3_mhm-home-security-ui_Dlatency\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      ES3idle:   ((if exists r[\"s3_mhm-home-security-img_B\"] then r[\"s3_mhm-home-security-img_B\"] else 0.0) + (if exists r[\"s3_mhm-home-security-ui_B\"] then r[\"s3_mhm-home-security-ui_B\"] else 0.0)) * 0.0001 / (1073741824.0 * 1024.0 * 1000.0)      ,\n      EDB:       ((if exists r[\"dynamodb_Events_Lsuccess\"] then r[\"dynamodb_Events_Lsuccess\"] else 0.0) + (if exists r[\"dynamodb_Users_Lsuccess\"] then r[\"dynamodb_Users_Lsuccess\"] else 0.0)) * 0.005 / (3600.0 * 1000.0),\n      EAPI:      (if exists r[\"api_API_LAPI\"] then r[\"api_API_LAPI\"] else 0.0) * 15.0 / (3600.0 * 1000.0),\n      ERekog:    (if exists r[\"rekognition_Rekognition_Tresponse\"] then r[\"rekognition_Rekognition_Tresponse\"] else 0.0) * 50.0 / (3600.0 * 1000.0),\n      PUE:       (if exists r[\"assumed_PUE\"] then r[\"assumed_PUE\"] else 1.5),\n      GEF:       (if exists r[\"grid_emission_factor\"] then r[\"grid_emission_factor\"] else 350.0)\n  }))\n  |> map(fn: (r) => ({\n      r with\n      ETotal: r.ELcompute + r.ELmemory + r.ELstorage + r.Enetwork + r.EDB + r.EAPI + r.ERekog + r.ES3active + r.ES3idle\n  }))\n  |> map(fn: (r) => ({\n      r with\n      SCI: r.ETotal * r.PUE * r.GEF\n  }))\nunion(tables: [results |> map(fn: (r) => ({ component: \"ELcompute\", value: r.ELcompute })), results |> map(fn: (r) => ({ component: \"ELmemory\", value: r.ELmemory })), results |> map(fn: (r) => ({ component: \"ELstorage\", value: r.ELstorage })), results |> map(fn: (r) => ({ component: \"Enetwork\", value: r.Enetwork })), results |> map(fn: (r) => ({ component: \"EDB\", value: r.EDB })), results |> map(fn: (r) => ({ component: \"EAPI\", value: r.EAPI })), results |> map(fn: (r) => ({ component: \"ES3active\", value: r.ES3active })), results |> map(fn: (r) => ({ component: \"ERekog\", value: r.ERekog })), results |> map(fn: (r) => ({ component: \"ES3idle\", value: r.ES3idle }))])"
    }
   ]
  }
 ]
}